SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [Minion].[EncryptTxt] (@PlainTxt VARCHAR(4000))
RETURNS VARBINARY(MAX)
WITH EXECUTE AS CALLER
AS

BEGIN
DECLARE @EncryptedTxt VARBINARY(MAX);

SET @EncryptedTxt = ENCRYPTBYCERT(CERT_ID('MinionEncrypt'), @PlainTxt)

RETURN @EncryptedTxt
END
GO
