SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE VIEW [dbo].[vwTMWTRANDB_Today]
AS
SELECT *  FROM [TMDBSQL].[dbo].[TMWTRANDB] WHERE ts_start > DATEDIFF(d,0,GETDATE()) or ts_start > DATEDIFF(d,0,GETDATE())
GO
