CREATE TABLE [dbo].[GRID]
(
[DealName] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DayPL] [decimal] (12, 2) NOT NULL,
[DayDiv] [decimal] (12, 2) NOT NULL,
[MonthPL] [decimal] (12, 2) NOT NULL,
[MonthDiv] [decimal] (12, 2) NOT NULL,
[Account] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Target] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Acquirer] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Strategy] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GrossSprd] [decimal] (12, 2) NOT NULL,
[UpsidePts] [decimal] (12, 2) NOT NULL,
[WeekSprd] [decimal] (12, 2) NOT NULL,
[UpDown] [decimal] (12, 2) NOT NULL,
[PctDnCap] [decimal] (12, 2) NOT NULL,
[DlrInvested] [decimal] (12, 2) NOT NULL,
[CloseProb] [decimal] (12, 2) NOT NULL,
[NumTarget] [int] NOT NULL,
[NumAcquirer] [int] NOT NULL,
[EquivPos] [int] NOT NULL,
[NetPos] [int] NOT NULL,
[UndlyPrice] [decimal] (12, 2) NOT NULL,
[AcqPrice] [decimal] (12, 2) NOT NULL,
[DlrNetPos] [decimal] (12, 2) NOT NULL,
[DealDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DealType] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Ratio] [decimal] (12, 2) NOT NULL,
[Weeks] [decimal] (12, 2) NOT NULL,
[UpsidePrc] [decimal] (12, 2) NOT NULL,
[TotalUpsd] [int] NOT NULL,
[DownPrice] [decimal] (12, 2) NOT NULL,
[ZShort] [decimal] (12, 2) NOT NULL,
[TargDnPts] [decimal] (12, 2) NOT NULL,
[AcqDnPts] [decimal] (12, 2) NOT NULL,
[TargTotDn] [int] NOT NULL,
[AcqTotDn] [int] NOT NULL,
[TotalDown] [int] NOT NULL,
[TotalSprd] [float] NOT NULL,
[AnnualSprd] [float] NOT NULL,
[PctTargDnCap] [decimal] (12, 2) NOT NULL,
[TargVote] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AcqVote] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[YearPL] [decimal] (12, 2) NOT NULL,
[YearDiv] [decimal] (12, 2) NOT NULL,
[PosPL] [decimal] (12, 2) NOT NULL,
[Unrealized] [decimal] (12, 2) NOT NULL,
[Fund] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DealSort] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NetDayPL] [decimal] (12, 2) NOT NULL,
[UpdateTime] [datetime2] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GRID] ADD CONSTRAINT [PK_GRID] PRIMARY KEY CLUSTERED ([UpdateTime], [Fund], [Account], [DealName]) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON [PRIMARY]
GO
