CREATE TABLE [dbo].[TMWSECDB]
(
[symbol] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ts_start] [datetime] NOT NULL,
[ts_end] [datetime] NULL,
[cusip] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[undsym] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[type] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[exchange] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[descr] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[strategy] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[memo] [varchar] (74) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shortratecode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[exdate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[divdate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[coupdate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[divfreq] [smallint] NULL,
[divamt] [real] NULL,
[coupon] [real] NULL,
[longrate] [real] NULL,
[shortrate] [real] NULL,
[ratio] [float] NULL,
[cvbuyprice] [float] NULL,
[face] [float] NULL,
[cvprice] [float] NULL,
[sizequal] [float] NULL,
[longmark] [float] NULL,
[shortmark] [float] NULL,
[prmult] [float] NULL,
[strike] [float] NULL,
[lastdivdate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priordivdate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastdivamt] [real] NULL,
[priordivamt] [real] NULL,
[coupfreq] [smallint] NULL,
[lastcoupdate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priorcoupdate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[issuedate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dateddate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[volatility1] [smallint] NULL,
[volatility2] [smallint] NULL,
[volatility3] [smallint] NULL,
[impvol] [smallint] NULL,
[investval] [real] NULL,
[sharesout] [float] NULL,
[rating] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[investvaltype] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[longmarkcode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shortmarkcode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[callprice] [real] NULL,
[putprice] [real] NULL,
[calldate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[putdate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sort] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[currency] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[country] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[earnshare] [real] NULL,
[cvsellprice] [float] NULL,
[margin] [float] NULL,
[secid] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[secfeeflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hedge] [real] NULL,
[cprice] [float] NULL,
[sprice] [float] NULL,
[prevmark] [float] NULL,
[markdate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[industry] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sector] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[invgrade] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[screwflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockatgrade] [real] NULL,
[stkpctdowngrade] [real] NULL,
[puttodate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[condcallprice] [real] NULL,
[condcalldate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[condcalltodate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prevmark2] [float] NULL,
[markdate2] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modelhedge] [real] NULL,
[active] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[liveflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cashpaydate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cashpayrate] [real] NULL,
[xlsymbol] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trader] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bucket] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accrualmethod] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[analyst] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[intsymbol] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[portmgr] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prevexchange] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ratioflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[subtype] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qsymbol] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[livemarkflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[optoverrideflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[swapflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[registeredflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[divrollflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[amountout] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TMWSECDB] ADD CONSTRAINT [PK_TMWSECDB] PRIMARY KEY CLUSTERED ([symbol], [ts_start] DESC) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
