CREATE TABLE [dbo].[TMWDEALDB]
(
[dealname] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ts_start] [datetime] NOT NULL,
[ts_end] [datetime] NULL,
[undsym] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[acqsym] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[type] [smallint] NULL,
[cashpct] [real] NULL,
[stockpct] [real] NULL,
[tndrpct] [real] NULL,
[cashamt] [float] NULL,
[ratio] [float] NULL,
[lowcollar] [float] NULL,
[highcollar] [float] NULL,
[outsidelow] [float] NULL,
[outsidehigh] [float] NULL,
[dealamt] [float] NULL,
[lowrange] [float] NULL,
[highrange] [float] NULL,
[revcollar] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[outflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[residual] [float] NULL,
[origprice] [float] NULL,
[origacq] [float] NULL,
[downprice] [float] NULL,
[d1date] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[d2date] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ds1symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ds1price] [real] NULL,
[ds2symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ds2price] [real] NULL,
[ds3symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ds3price] [real] NULL,
[ds4symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ds4price] [real] NULL,
[ds5symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ds5price] [real] NULL,
[ds6symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ds6price] [real] NULL,
[ds7symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ds7price] [real] NULL,
[ds8symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ds8price] [real] NULL,
[ds9symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ds9price] [real] NULL,
[ds10symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ds10price] [real] NULL,
[desc] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cashelect] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[canbuy] [int] NULL,
[charge] [float] NULL,
[dealdisp] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zs1symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zs1price] [real] NULL,
[zs2symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zs2price] [real] NULL,
[zs3symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zs3price] [real] NULL,
[zs4symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zs4price] [real] NULL,
[zs5symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zs5price] [real] NULL,
[zs6symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zs6price] [real] NULL,
[zs7symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zs7price] [real] NULL,
[zs8symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zs8price] [real] NULL,
[zs9symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zs9price] [real] NULL,
[zs10symbol] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zs10price] [real] NULL,
[zshortprice] [float] NULL,
[other1] [char] (214) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[other2] [char] (214) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[other3] [char] (214) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[numadditional] [smallint] NULL,
[secsharesflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[definitive] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[initials1] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[initials2] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dealreport] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nondefcanbuy] [int] NULL,
[defcanbuy] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[category] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prevdown] [char] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prevzshort] [char] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prevadd1] [char] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prevadd2] [char] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prevadd3] [char] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[secondtier] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[strategy] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[currency] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[upsidemult] [float] NULL,
[extracash] [float] NULL,
[altclose] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altupside] [float] NULL,
[desc1] [varchar] (214) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TMWDEALDB] ADD CONSTRAINT [PK_TMWDEALDB] PRIMARY KEY CLUSTERED ([dealname], [ts_start] DESC) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
