CREATE TABLE [dbo].[TMWPOSDB]
(
[account] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[strategy] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[symbol] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ts_start] [datetime] NOT NULL,
[ts_end] [datetime] NULL,
[currency] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shortratecode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[longrate] [real] NULL,
[shortrate] [real] NULL,
[fxrate] [real] NULL,
[ratio] [real] NULL,
[hedge] [real] NULL,
[mark] [float] NULL,
[h1offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h1percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h1longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h1shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h1longratefrac] [smallint] NULL,
[h1shortratefrac] [smallint] NULL,
[h1mark] [real] NULL,
[h2offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h2percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h2longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h2shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h2longratefrac] [smallint] NULL,
[h2shortratefrac] [smallint] NULL,
[h2mark] [real] NULL,
[h3offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h3percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h3longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h3shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h3longratefrac] [smallint] NULL,
[h3shortratefrac] [smallint] NULL,
[h3mark] [real] NULL,
[h4offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h4percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h4longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h4shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h4longratefrac] [smallint] NULL,
[h4shortratefrac] [smallint] NULL,
[h4mark] [real] NULL,
[h5offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h5percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h5longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h5shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h5longratefrac] [smallint] NULL,
[h5shortratefrac] [smallint] NULL,
[h5mark] [real] NULL,
[h6offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h6percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h6longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h6shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h6longratefrac] [smallint] NULL,
[h6shortratefrac] [smallint] NULL,
[h6mark] [real] NULL,
[h7offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h7percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h7longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h7shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h7longratefrac] [smallint] NULL,
[h7shortratefrac] [smallint] NULL,
[h7mark] [real] NULL,
[h8offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h8percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h8longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h8shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h8longratefrac] [smallint] NULL,
[h8shortratefrac] [smallint] NULL,
[h8mark] [real] NULL,
[h9offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h9percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h9longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h9shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h9longratefrac] [smallint] NULL,
[h9shortratefrac] [smallint] NULL,
[h9mark] [real] NULL,
[h10offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h10percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h10longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h10shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h10longratefrac] [smallint] NULL,
[h10shortratefrac] [smallint] NULL,
[h10mark] [real] NULL,
[h11offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h11percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h11longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h11shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h11longratefrac] [smallint] NULL,
[h11shortratefrac] [smallint] NULL,
[h11mark] [real] NULL,
[h12offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h12percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h12longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h12shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h12longratefrac] [smallint] NULL,
[h12shortratefrac] [smallint] NULL,
[h12mark] [real] NULL,
[h13offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h13percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h13longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h13shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h13longratefrac] [smallint] NULL,
[h13shortratefrac] [smallint] NULL,
[h13mark] [real] NULL,
[h14offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h14percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h14longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h14shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h14longratefrac] [smallint] NULL,
[h14shortratefrac] [smallint] NULL,
[h14mark] [real] NULL,
[h15offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h15percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h15longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h15shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h15longratefrac] [smallint] NULL,
[h15shortratefrac] [smallint] NULL,
[h15mark] [real] NULL,
[h16offset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h16percent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h16longrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h16shortrateint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h16longratefrac] [smallint] NULL,
[h16shortratefrac] [smallint] NULL,
[h16mark] [real] NULL,
[openstart] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[openpos] [int] NULL,
[openreal] [float] NULL,
[opencost] [float] NULL,
[opencash] [float] NULL,
[openmark] [float] NULL,
[opendirecv] [float] NULL,
[opendipaid] [float] NULL,
[opencprecv] [float] NULL,
[opencppaid] [float] NULL,
[opencomm] [float] NULL,
[openaccrued] [float] NULL,
[opensecfee] [float] NULL,
[opentktcharge] [float] NULL,
[daystart] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[daypos] [int] NULL,
[dayreal] [float] NULL,
[daycost] [float] NULL,
[daycash] [float] NULL,
[daymark] [float] NULL,
[daydirecv] [float] NULL,
[daydipaid] [float] NULL,
[daycprecv] [float] NULL,
[daycppaid] [float] NULL,
[daycomm] [float] NULL,
[dayaccrued] [float] NULL,
[daysecfee] [float] NULL,
[daytktcharge] [float] NULL,
[monthstart] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[monthpos] [int] NULL,
[monthreal] [float] NULL,
[monthcost] [float] NULL,
[monthcash] [float] NULL,
[monthmark] [float] NULL,
[monthdirecv] [float] NULL,
[monthdipaid] [float] NULL,
[monthcprecv] [float] NULL,
[monthcppaid] [float] NULL,
[monthcomm] [float] NULL,
[monthaccrued] [float] NULL,
[monthsecfee] [float] NULL,
[monthtktcharge] [float] NULL,
[yearstart] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yearpos] [int] NULL,
[yearreal] [float] NULL,
[yearcost] [float] NULL,
[yearcash] [float] NULL,
[yearmark] [float] NULL,
[yeardirecv] [float] NULL,
[yeardipaid] [float] NULL,
[yearcprecv] [float] NULL,
[yearcppaid] [float] NULL,
[yearcomm] [float] NULL,
[yearaccrued] [float] NULL,
[yearsecfee] [float] NULL,
[yeartktcharge] [float] NULL,
[lastmonthstart] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastmonthpos] [int] NULL,
[lastmonthreal] [float] NULL,
[lastmonthcost] [float] NULL,
[lastmonthcash] [float] NULL,
[lastmonthmark] [float] NULL,
[lastmonthdirecv] [float] NULL,
[lastmonthdipaid] [float] NULL,
[lastmonthcprecv] [float] NULL,
[lastmonthcppaid] [float] NULL,
[lastmonthcomm] [float] NULL,
[lastmonthaccrued] [float] NULL,
[lastmonthsecfee] [float] NULL,
[lastmonthtktcharge] [float] NULL,
[lastyearstart] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastyearpos] [int] NULL,
[lastyearreal] [float] NULL,
[lastyearcost] [float] NULL,
[lastyearcash] [float] NULL,
[lastyearmark] [float] NULL,
[lastyeardirecv] [float] NULL,
[lastyeardipaid] [float] NULL,
[lastyearcprecv] [float] NULL,
[lastyearcppaid] [float] NULL,
[lastyearcomm] [float] NULL,
[lastyearaccured] [float] NULL,
[lastyearsecfee] [float] NULL,
[lastyeartktcharge] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TMWPOSDB] ADD CONSTRAINT [PK_TMWPOSDB] PRIMARY KEY CLUSTERED ([account], [strategy], [symbol], [ts_start] DESC) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_account] ON [dbo].[TMWPOSDB] ([account]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20210423-084930] ON [dbo].[TMWPOSDB] ([strategy], [symbol], [account], [ts_start]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20210423-084650] ON [dbo].[TMWPOSDB] ([symbol], [account], [strategy], [ts_start]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20210423-155726] ON [dbo].[TMWPOSDB] ([ts_end]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
