CREATE TABLE [dbo].[TMWTRANDB]
(
[seqnum] [int] NOT NULL,
[account] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[strategy] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[symbol] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[tradedate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[entrydate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[tag] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ts_start] [datetime] NOT NULL,
[ts_end] [datetime] NULL,
[type] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comment] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[auth] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rectype] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[settle] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[entryflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[quantity] [int] NULL,
[price] [float] NULL,
[comm] [float] NULL,
[money] [float] NULL,
[broker] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userid] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[interest] [float] NULL,
[interestflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[exchange] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[secfee] [real] NULL,
[tktcharge] [real] NULL,
[contrabroker] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[clearance] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[blotter] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[route] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[openclose] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tradetime] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[settleflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[asof] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[id] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[destination] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cxlsentflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[acctsubtype] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contraacct] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contracode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[block] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fxrate] [float] NULL,
[fxmoney] [float] NULL,
[ordersymbol] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderdate] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderentry] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordertag] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tradetag] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[undprice] [float] NULL,
[tradeflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[regid] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[regtime] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cxltime] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bidlist] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[filler1] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cxlentry] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cxltag] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seqnum2] [int] NULL,
[regstatus] [smallint] NULL,
[reportflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[location] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[regfee] [real] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TMWTRANDB] ADD CONSTRAINT [PK_TMWTRANDB] PRIMARY KEY CLUSTERED ([seqnum], [account], [strategy], [symbol], [entrydate], [tag], [ts_start] DESC) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
