CREATE TABLE [Minion].[CheckDBLogDetails]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ExecutionDateTime] [datetime] NULL,
[STATUS] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PctComplete] [tinyint] NULL,
[DBName] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CheckDBName] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServerLabel] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NETBIOSName] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsRemote] [bit] NULL,
[PreferredServer] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredDBName] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RemoteCheckDBMode] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RemoteRestoreMode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsClustered] [bit] NULL,
[IsInAG] [bit] NULL,
[IsPrimaryReplica] [bit] NULL,
[DBType] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OpName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SchemaName] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TableName] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IndexName] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IndexID] [bigint] NULL,
[IndexType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroupOrder] [int] NULL,
[GroupDBOrder] [int] NULL,
[SizeInMB] [float] NULL,
[TimeLimitInMins] [int] NULL,
[EstimatedTimeInSecs] [int] NULL,
[EstimatedKBperMS] [float] NULL,
[LastOpTimeInSecs] [int] NULL,
[IncludeRemoteInTimeLimit] [int] NULL,
[OpBeginTime] [datetime] NULL,
[OpEndTime] [datetime] NULL,
[OpRunTimeInSecs] [float] NULL,
[CustomSnapshot] [bit] NULL,
[MaxSnapshotSizeInKB] [float] NULL,
[CheckDBCmd] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllocationErrors] [int] NULL,
[ConsistencyErrors] [int] NULL,
[NoIndex] [bit] NULL,
[RepairOption] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RepairOptionAgree] [bit] NULL,
[WithRollback] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllErrorMsgs] [bit] NULL,
[ExtendedLogicalChecks] [bit] NULL,
[NoInfoMsgs] [bit] NULL,
[IsTabLock] [bit] NULL,
[IntegrityCheckLevel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DisableDOP] [bit] NULL,
[LockDBMode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ResultMode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HistRetDays] [int] NULL,
[PushToMinion] [bit] NULL,
[MinionTriggerPath] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AutoRepair] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AutoRepairTime] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastCheckDateTime] [datetime] NULL,
[LastCheckResult] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DBPreCodeStartDateTime] [datetime] NULL,
[DBPreCodeEndDateTime] [datetime] NULL,
[DBPreCodeTimeInSecs] [int] NULL,
[DBPreCode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DBPostCodeStartDateTime] [datetime] NULL,
[DBPostCodeEndDateTime] [datetime] NULL,
[DBPostCodeTimeInSecs] [int] NULL,
[DBPostCode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TablePreCodeStartDateTime] [datetime] NULL,
[TablePreCodeEndDateTime] [datetime] NULL,
[TablePreCodeTimeInSecs] [int] NULL,
[TablePreCode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TablePostCodeStartDateTime] [datetime] NULL,
[TablePostCodeEndDateTime] [datetime] NULL,
[TablePostCodeTimeInSecs] [int] NULL,
[TablePostCode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StmtPrefix] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StmtSuffix] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProcessingThread] [tinyint] NULL,
[Warnings] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [nonExecDBOp] ON [Minion].[CheckDBLogDetails] ([ExecutionDateTime], [CheckDBName], [OpName]) INCLUDE ([ID]) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [nonExecStatusDBName] ON [Minion].[CheckDBLogDetails] ([ExecutionDateTime], [DBName]) INCLUDE ([STATUS]) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [clustID] ON [Minion].[CheckDBLogDetails] ([ID]) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [nonOpEndTime] ON [Minion].[CheckDBLogDetails] ([OpEndTime] DESC, [DBName], [OpName], [SchemaName], [TableName]) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON [PRIMARY]
GO
