CREATE TABLE [Minion].[BackupLogDetails]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ExecutionDateTime] [datetime] NULL,
[STATUS] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PctComplete] [tinyint] NULL,
[DBName] [sys].[sysname] NULL,
[ServerLabel] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NETBIOSName] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsClustered] [bit] NULL,
[IsInAG] [bit] NULL,
[IsPrimaryReplica] [bit] NULL,
[DBType] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupStartDateTime] [datetime] NULL,
[BackupEndDateTime] [datetime] NULL,
[BackupTimeInSecs] [float] NULL,
[MBPerSec] [float] NULL,
[BackupCmd] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SizeInMB] [float] NULL,
[StmtOnly] [bit] NULL,
[READONLY] [tinyint] NULL,
[BackupGroupOrder] [int] NULL,
[BackupGroupDBOrder] [int] NULL,
[NumberOfFiles] [tinyint] NULL,
[Buffercount] [int] NULL,
[MaxTransferSize] [bigint] NULL,
[MemoryLimitInMB] [bigint] NULL,
[TotalBufferSpaceInMB] [bigint] NULL,
[FileSystemIOAlignInKB] [int] NULL,
[SetsOfBuffers] [tinyint] NULL,
[Verify] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Compression] [bit] NULL,
[FileAction] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileActionTime] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileActionBeginDateTime] [datetime] NULL,
[FileActionEndDateTime] [datetime] NULL,
[FileActionTimeInSecs] [int] NULL,
[UnCompressedBackupSizeMB] [int] NULL,
[CompressedBackupSizeMB] [int] NULL,
[CompressionRatio] [float] NULL,
[COMPRESSIONPct] [numeric] (20, 1) NULL,
[BackupRetHrs] [tinyint] NULL,
[BackupLogging] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupLoggingRetDays] [smallint] NULL,
[DelFileBefore] [bit] NULL,
[DBPreCode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DBPostCode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DBPreCodeStartDateTime] [datetime] NULL,
[DBPreCodeEndDateTime] [datetime] NULL,
[DBPreCodeTimeInSecs] [int] NULL,
[DBPostCodeStartDateTime] [datetime] NULL,
[DBPostCodeEndDateTime] [datetime] NULL,
[DBPostCodeTimeInSecs] [int] NULL,
[IncludeDBs] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExcludeDBs] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegexDBsExcluded] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Verified] [bit] NULL,
[VerifyStartDateTime] [datetime] NULL,
[VerifyEndDateTime] [datetime] NULL,
[VerifyTimeInSecs] [int] NULL,
[IsInit] [bit] NULL,
[IsFormat] [bit] NULL,
[IsCheckSum] [bit] NULL,
[BlockSize] [bigint] NULL,
[Descr] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsCopyOnly] [bit] NULL,
[IsSkip] [bit] NULL,
[BackupName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupErrorMgmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MediaName] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MediaDescription] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExpireDateInHrs] [int] NULL,
[RetainDays] [smallint] NULL,
[MirrorBackup] [bit] NULL,
[DynamicTuning] [bit] NULL,
[ShrinkLogOnLogBackup] [bit] NULL,
[ShrinkLogThresholdInMB] [int] NULL,
[ShrinkLogSizeInMB] [int] NULL,
[PreBackupLogSizeInMB] [float] NULL,
[PreBackupLogUsedPct] [float] NULL,
[PostBackupLogSizeInMB] [float] NULL,
[PostBackupLogUsedPct] [int] NULL,
[PreBackupLogReuseWait] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostBackupLogReuseWait] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLFs] [bigint] NULL,
[FileList] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsTDE] [bit] NULL,
[BackupCert] [bit] NULL,
[CertPword] [varbinary] (max) NULL,
[IsEncryptedBackup] [bit] NULL,
[BackupEncryptionCertName] [nchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupEncryptionAlgorithm] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupEncryptionCertThumbPrint] [varbinary] (32) NULL,
[DeleteFilesStartDateTime] [datetime] NULL,
[DeleteFilesEndDateTime] [datetime] NULL,
[DeleteFilesTimeInSecs] [int] NULL,
[Warnings] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [nonExecutionDateTime] ON [Minion].[BackupLogDetails] ([ExecutionDateTime], [DBName], [BackupType]) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [clustID] ON [Minion].[BackupLogDetails] ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
