CREATE TABLE [Minion].[IndexSettingsTable]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[DBName] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SchemaName] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TableName] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Exclude] [bit] NULL,
[ReindexGroupOrder] [int] NULL,
[ReindexOrder] [int] NULL,
[ReorgThreshold] [tinyint] NULL,
[RebuildThreshold] [tinyint] NULL,
[FILLFACTORopt] [tinyint] NULL,
[PadIndex] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ONLINEopt] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SortInTempDB] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAXDOPopt] [tinyint] NULL,
[DataCompression] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GetRowCT] [bit] NULL,
[GetPostFragLevel] [bit] NULL,
[UpdateStatsOnDefrag] [bit] NULL,
[StatScanOption] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IgnoreDupKey] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatsNoRecompute] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowRowLocks] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowPageLocks] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WaitAtLowPriority] [bit] NULL,
[MaxDurationInMins] [int] NULL,
[AbortAfterWait] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PushToMinion] [bit] NULL,
[LogIndexPhysicalStats] [bit] NULL,
[IndexScanMode] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TablePreCode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TablePostCode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LogProgress] [bit] NULL,
[LogRetDays] [smallint] NULL,
[PartitionReindex] [bit] NULL,
[isLOB] [bit] NULL,
[TableType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncludeUsageDetails] [bit] NULL,
[StmtPrefix] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StmtSuffix] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RebuildHeap] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [Minion].[IndexSettingsTable] ADD CONSTRAINT [ckRbuildGTReorgTable] CHECK (([RebuildThreshold]>[ReorgThreshold]))
GO
