CREATE TABLE [Minion].[BackupFiles]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ExecutionDateTime] [datetime] NULL,
[Op] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DBName] [sys].[sysname] NOT NULL,
[ServerLabel] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NETBIOSName] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupLocType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupDrive] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupPath] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullPath] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullFileName] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateLogic] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Extension] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RetHrs] [int] NULL,
[IsMirror] [bit] NULL,
[ToBeDeleted] [datetime] NULL,
[DeleteDateTime] [datetime] NULL,
[IsDeleted] [bit] NULL,
[IsArchive] [bit] NULL,
[BackupSizeInMB] [numeric] (15, 3) NULL,
[BackupName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupDescription] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExpirationDate] [datetime] NULL,
[Compressed] [bit] NULL,
[POSITION] [tinyint] NULL,
[DeviceType] [tinyint] NULL,
[UserName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DatabaseName] [sys].[sysname] NULL,
[DatabaseVersion] [int] NULL,
[DatabaseCreationDate] [datetime] NULL,
[BackupSizeInBytes] [bigint] NULL,
[FirstLSN] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastLSN] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CheckpointLSN] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DatabaseBackupLSN] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupStartDate] [datetime] NULL,
[BackupFinishDate] [datetime] NULL,
[SortOrder] [int] NULL,
[CODEPAGE] [int] NULL,
[UnicodeLocaleId] [int] NULL,
[UnicodeComparisonStyle] [int] NULL,
[CompatibilityLevel] [int] NULL,
[SoftwareVendorId] [int] NULL,
[SoftwareVersionMajor] [int] NULL,
[SoftwareVersionMinor] [int] NULL,
[SovtwareVersionBuild] [int] NULL,
[MachineName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Flags] [int] NULL,
[BindingID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecoveryForkID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COLLATION] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FamilyGUID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasBulkLoggedData] [bit] NULL,
[IsSnapshot] [bit] NULL,
[IsReadOnly] [bit] NULL,
[IsSingleUser] [bit] NULL,
[HasBackupChecksums] [bit] NULL,
[IsDamaged] [bit] NULL,
[BeginsLogChain] [bit] NULL,
[HasIncompleteMeatdata] [bit] NULL,
[IsForceOffline] [bit] NULL,
[IsCopyOnly] [bit] NULL,
[FirstRecoveryForkID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ForkPointLSN] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecoveryModel] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DifferentialBaseLSN] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DifferentialBaseGUID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupTypeDescription] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupSetGUID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompressedBackupSize] [bigint] NULL,
[CONTAINMENT] [tinyint] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [nonExecutionDateTime] ON [Minion].[BackupFiles] ([ExecutionDateTime], [IsDeleted], [DBName]) INCLUDE ([ID], [BackupType], [FullFileName], [IsMirror]) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [clustID] ON [Minion].[BackupFiles] ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [nonDeletedDBName] ON [Minion].[BackupFiles] ([IsDeleted], [DBName], [IsArchive], [ID]) INCLUDE ([ExecutionDateTime], [Op], [BackupType], [FullFileName], [IsMirror], [BackupSizeInMB]) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON [PRIMARY]
GO
