CREATE TABLE [Minion].[CheckDBSettingsDB]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[DBName] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Port] [int] NULL,
[OpLevel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OpName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Exclude] [bit] NULL,
[GroupOrder] [int] NULL,
[GroupDBOrder] [int] NULL,
[NoIndex] [bit] NULL,
[RepairOption] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RepairOptionAgree] [bit] NULL,
[WithRollback] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllErrorMsgs] [bit] NULL,
[ExtendedLogicalChecks] [bit] NULL,
[NoInfoMsgs] [bit] NULL,
[IsTabLock] [bit] NULL,
[IntegrityCheckLevel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DisableDOP] [bit] NULL,
[IsRemote] [bit] NULL,
[IncludeRemoteInTimeLimit] [bit] NULL,
[PreferredServer] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredServerPort] [int] NULL,
[PreferredDBName] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RemoteJobName] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RemoteCheckDBMode] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RemoteRestoreMode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DropRemoteDB] [bit] NULL,
[DropRemoteJob] [bit] NULL,
[LockDBMode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ResultMode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HistRetDays] [int] NULL,
[PushToMinion] [bit] NULL,
[MinionTriggerPath] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AutoRepair] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AutoRepairTime] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultSchema] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DBPreCode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DBPostCode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TablePreCode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TablePostCode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StmtPrefix] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StmtSuffix] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DBInternalThreads] [tinyint] NULL CONSTRAINT [DF_CheckDBSettingsDB_InternalThreads] DEFAULT ((1)),
[DefaultTimeEstimateMins] [int] NULL,
[LogSkips] [bit] NULL,
[BeginTime] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndTime] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DayOfWeek] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsActive] [bit] NULL,
[Comment] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [Minion].[CheckDBSettingsDB] ADD CONSTRAINT [CheckDBSettingsDB_InternalThreads] CHECK (([DBInternalThreads]>=(1)))
GO
